// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolGrades.Data;

namespace SchoolGrades.Migrations
{
    [DbContext(typeof(SchoolGradesDbContext))]
    [Migration("20201119003102_fields required and GradeLiteral field added")]
    partial class fieldsrequiredandGradeLiteralfieldadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SchoolGrades.Models.SchoolGrades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeLiteral")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
